version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: yourwordpresspw
       MYSQL_DATABASE: exampledb    
       MYSQL_USER: example
       MYSQL_PASSWORD: example

   wp:
     depends_on:
       - db
     image: wordpress:latest
     deploy:
       replicas: 2
     ports:
       - "8000:80"
     restart: always
     #volumes:                        #Optional - Mount a dir if you want custom data available in /var/www/html
      # - .:/var/www/html
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: example
       WORDPRESS_DB_PASSWORD: example
       WORDPRESS_DB_NAME: exampledb
volumes:
    db_data: {}